theme: jekyll-theme-architect
title: Welcome to Mandy's page
description: Feel free to navigate this page. You can call me either Mandy or Mengyan, and I won't get offensive if you mispronouce my Chinese name haha! 
description: just testing if they allow two...
